### ISSUE TITLE
Molecule 6 compatibility

### ISSUE THREAD

**Issue by p3l1** [meffie/molecule-proxmox#11]
Hey there,

are there any plans to support newer Molecule versions in the future? Right now Molecule 4.0.1 is a fixed dependency.

Thanks in advance

**Comment by meffie** [comment]
On Wed, 23 Aug 2023 02:12:31 -0700
Philipp Herzog ***@***.***> wrote:

> Hey there,
> 
> are there any plans to support newer Molecule versions in the future? Right now Molecule 4.0.1 is a fixed dependency.
> 
> Thanks in advance

Yes, molecule broke out of tree plugins by changing how the schema validation
is done. It seems that plugins should now be able to implement their own
schema validation, so that is what I'm currently investigating.

Thanks,
Mike

**Comment by p3l1** [comment]
That sounds great, looking forward to it!

Thanks for your response.
